// <auto-generated />
namespace Apo_ChanService.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Update20171102 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Update20171102));
        
        string IMigrationMetadata.Id
        {
            get { return "201711020343128_Update20171102"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
